Backend/108/emai verification
kohdataan/kohdataan-backend pull request #114
Opened 2019-12-12 08:27 UTC by KaroliinaM

* Add email verified field to the user table. Boolean, default false.
* Add a table for email verification. Colums userid and uuid
* Routes for sending verification message and the actual verification
* send the verification message: search the user, create uuid and send it to teh user
* verification: find the user based on the uuid and set account verified

2019-12-16 23:25 UTC, TerriFin approved these changes
Looks good, only thing i would do is to delete the uuid tokens as they are used, but works without it also.

2019-12-23 13:14 UTC, Pninja requested changes
Good job! Only thing I noticed is that when migrating, older users don't have any value in column `emailVerified`, but its not allowed to be null. Hence, older user's can't update their profiles anymore unless verifying their email (which is not possible currently from frontend). I think this should be handled either by filling `emailVerified` as `false` for older users, or completing frontend verification functionality before merging this.

I would suggest changing the migration to:
```
module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.addColumn('Users', 'emailVerified', {
      type: Sequelize.BOOLEAN,
      defaultValue: false,
    })
  },

  down: (queryInterface, Sequelize) => {
    return queryInterface.removeColumn(
      'Users',
      'emailVerified',
      Sequelize.BOOLEAN
    )
  },
}
```
So that adding the column also adds default values. :)

2019-12-23 13:14 UTC, Pninja commented on node/controllers/emailverification/index.js
> +      return EmailVerificationUuid.findOne({ where: { userId: user.id } })
If I read this correctly, user will always receive the same uuid, that is generated on the first verification request. 
Since the user can't login directly from the verification link, and still needs password in addition, I don't see any problems here using always the same token. But if we want (in the future) to do the verification so, that user can also directly login by clicking the verification link, then we should have expiration time for uuids and remove those after they have been used, and always generate new ones with each request. This is because if someone would get the uuid from somewhere (for example by bruteforcing), then they could also log in with another person's account. Anyway, this is fine for now. 👍

2020-01-20 09:28 UTC, Pninja requested changes
Looks good! Just one question about the migration.

2020-01-20 09:28 UTC, Pninja commented on node/database/migrations/20191220142946-add-used-in-password-reset-uuid.js
> +      defaultValue: false,
Is this supposed to be in "addEmailVerifiationField" migration (also)?

2020-01-21 12:45 UTC, Pninja approved these changes

2020-01-21 12:47 UTC, merged